// Product data generated from images in assets folder
export const products = [
  // Original products with minimal data
  {
    id: 1,
    name: "Cake 1",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_7210-Photoroom.jpg",
    category: "Birthday Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 2,
    name: "Cake 2",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4287-Photoroom.jpg",
    category: "Roll Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Round"
  },
  {
    id: 3,
    name: "Cake 3",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4290-Photoroom.jpg",
    category: "Dubai Chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 4,
    name: "Cake 4",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4293-Photoroom.jpg",
    category: "Mini Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 5,
    name: "Cake 5",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4296-Photoroom.jpg",
    category: "Desserts in a Cup",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 6,
    name: "Cake 6",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4302-Photoroom.jpg",
    category: "Classic Desserts",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 7,
    name: "Cake 7",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4317-Photoroom.jpg",
    category: "Custom Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Heart"
  },
  {
    id: 8,
    name: "Cake 8",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4319-Photoroom.jpg",
    category: "Occasion Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Round"
  },
  {
    id: 9,
    name: "Cake 9",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4403-Photoroom.jpg",
    category: "Fruit Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 10,
    name: "Cake 10",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4528-Photoroom.jpg",
    category: "Birthday Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Custom"
  },
  {
    id: 11,
    name: "Cake 11",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4532-Photoroom.jpg",
    category: "Roll Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Round"
  },
  {
    id: 12,
    name: "Cake 12",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4560-Photoroom.jpg",
    category: "Dubai Chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 13,
    name: "Cake 13",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5627-Photoroom.jpg",
    category: "Mini Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Heart"
  },
  {
    id: 14,
    name: "Cake 14",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5283-Photoroom.jpg",
    category: "Desserts in a Cup",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 15,
    name: "Cake 15",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5170-Photoroom.jpg",
    category: "Classic Desserts",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Square"
  },
  {
    id: 16,
    name: "Cake 16",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5351-Photoroom.jpg",
    category: "Custom Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Round"
  },
  {
    id: 17,
    name: "Cake 17",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5249-Photoroom.jpg",
    category: "Occasion Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Heart"
  },
  {
    id: 18,
    name: "Cake 18",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5795-Photoroom.jpg",
    category: "Fruit Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Square"
  },
  {
    id: 19,
    name: "Cake 19",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5793-Photoroom.jpg",
    category: "Birthday Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Round"
  },
  {
    id: 20,
    name: "Cake 20",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6018-Photoroom.jpg",
    category: "Roll Cakes",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 21,
    name: "Cake 21",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5290-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 22,
    name: "Cake 22",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5461-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Square"
  },
  {
    id: 23,
    name: "Cake 23",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5177-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Heart"
  },
  {
    id: 24,
    name: "Cake 24",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5854-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 25,
    name: "Cake 25",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5458-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 26,
    name: "Cake 26",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6562-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 27,
    name: "Cake 27",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5895-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 28,
    name: "Cake 28",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5515-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 29,
    name: "Cake 29",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5497-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 30,
    name: "Cake 30",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5997-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 31,
    name: "Cake 31",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1842-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Square"
  },
  {
    id: 32,
    name: "Cake 32",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1861-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Heart"
  },
  {
    id: 33,
    name: "Cake 33",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1863-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 34,
    name: "Cake 34",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1879-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 35,
    name: "Cake 35",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1884-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 36,
    name: "Cake 36",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1894-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 37,
    name: "Cake 37",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1901-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 38,
    name: "Cake 38",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1906-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 39,
    name: "Cake 39",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1911-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 40,
    name: "Cake 40",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1925-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 41,
    name: "Cake 41",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1945-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 42,
    name: "Cake 42",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1949-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 43,
    name: "Cake 43",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1954-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 44,
    name: "Cake 44",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1956-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 45,
    name: "Cake 45",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1958-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 46,
    name: "Cake 46",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1991-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 47,
    name: "Cake 47",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_1992-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 48,
    name: "Cake 48",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2015-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 49,
    name: "Cake 49",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2029-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 50,
    name: "Cake 50",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2034-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 51,
    name: "Cake 51",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2055-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 52,
    name: "Cake 52",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2056-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 53,
    name: "Cake 53",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2058-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 54,
    name: "Cake 54",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2071-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 55,
    name: "Cake 55",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2075-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 56,
    name: "Cake 56",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2086-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 57,
    name: "Cake 57",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2089-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 58,
    name: "Cake 58",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2091-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 59,
    name: "Cake 59",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2092-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 60,
    name: "Cake 60",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2094-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 61,
    name: "Cake 61",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2095-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 62,
    name: "Cake 62",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2096-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 63,
    name: "Cake 63",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2101-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 64,
    name: "Cake 64",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2106-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 65,
    name: "Cake 65",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2115-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 66,
    name: "Cake 66",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2116-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 67,
    name: "Cake 67",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2128-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 68,
    name: "Cake 68",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2131-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 69,
    name: "Cake 69",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2151-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 70,
    name: "Cake 70",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2156-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 71,
    name: "Cake 71",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2157-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 72,
    name: "Cake 72",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2159-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 73,
    name: "Cake 73",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2160-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 74,
    name: "Cake 74",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2182-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 75,
    name: "Cake 75",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2186-Photoroom.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 76,
    name: "Cake 76",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2191-Photoroom.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 77,
    name: "Cake 77",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2194-Photoroom.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 78,
    name: "Cake 78",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2204-Photoroom.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 79,
    name: "Cake 79",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2210.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 80,
    name: "Cake 80",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2219.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 81,
    name: "Cake 81",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2222.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 82,
    name: "Cake 82",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2224.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 83,
    name: "Cake 83",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2225.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 84,
    name: "Cake 84",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2226.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 85,
    name: "Cake 85",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2227.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 86,
    name: "Cake 86",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2228.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 87,
    name: "Cake 87",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2240.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 88,
    name: "Cake 88",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2241.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 89,
    name: "Cake 89",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2255.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 90,
    name: "Cake 90",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2279.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 91,
    name: "Cake 91",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_2281.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 92,
    name: "Cake 92",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3927.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 93,
    name: "Cake 93",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3928.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 94,
    name: "Cake 94",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3929.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 95,
    name: "Cake 95",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3930.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 96,
    name: "Cake 96",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3949.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 97,
    name: "Cake 97",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3962.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 98,
    name: "Cake 98",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3965.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 99,
    name: "Cake 99",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3980.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 100,
    name: "Cake 100",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_3990.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 101,
    name: "Cake 101",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4561.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 102,
    name: "Cake 102",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4570.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 103,
    name: "Cake 103",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4571.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 104,
    name: "Cake 104",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4588.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 105,
    name: "Cake 105",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4589.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 106,
    name: "Cake 106",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4598.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 107,
    name: "Cake 107",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4602.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 108,
    name: "Cake 108",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4603.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 109,
    name: "Cake 109",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4604.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 110,
    name: "Cake 110",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4638.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 111,
    name: "Cake 111",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4642.jpg",
    category: "chocolate", 
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 112,
    name: "Cake 112",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4658.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 113,
    name: "Cake 113",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4662.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 114,
    name: "Cake 114",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4695.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 115,
    name: "Cake 115",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4701.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 116,
    name: "Cake 116",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4703.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 117,
    name: "Cake 117",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4705.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 118,
    name: "Cake 118",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4712.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 119,
    name: "Cake 119",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4721.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 120,
    name: "Cake 120",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4729.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 121,
    name: "Cake 121",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4743.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 122,
    name: "Cake 122",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4753.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 123,
    name: "Cake 123",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4754.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 124,
    name: "Cake 124",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4756.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 125,
    name: "Cake 125",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4757.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 126,
    name: "Cake 126",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4770.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 127,
    name: "Cake 127",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4783.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 128,
    name: "Cake 128",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4784.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 129,
    name: "Cake 129",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4785.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 130,
    name: "Cake 130",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4802.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 131,
    name: "Cake 131",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4804.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 132,
    name: "Cake 132",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4805.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 133,
    name: "Cake 133",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4818.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 134,
    name: "Cake 134",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4820.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 135,
    name: "Cake 135",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4822.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 136,
    name: "Cake 136",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4823.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 137,
    name: "Cake 137",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4835.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 138,
    name: "Cake 138",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4836.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 139,
    name: "Cake 139",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4841.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 140,
    name: "Cake 140",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4851.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 141,
    name: "Cake 141",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4867.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 142,
    name: "Cake 142",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4873.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 143,
    name: "Cake 143",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4898.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 144,
    name: "Cake 144",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4901.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 145,
    name: "Cake 145",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4907.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 146,
    name: "Cake 146",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4910.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 147,
    name: "Cake 147",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4924.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 148,
    name: "Cake 148",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4940.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 149,
    name: "Cake 149",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4942.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 150,
    name: "Cake 150",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4955.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 151,
    name: "Cake 151",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_4962.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 200,
    name: "Cake 200",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5129.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 250,
    name: "Cake 250",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5254.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 300,
    name: "Cake 300",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5308.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 350,
    name: "Cake 350",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5398.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 400,
    name: "Cake 400",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5552.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 450,
    name: "Cake 450",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_5873.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 475,
    name: "Cake 475",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6432.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 480,
    name: "Cake 480",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6570.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 485,
    name: "Cake 485",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6673.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 490,
    name: "Cake 490",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6726.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 495,
    name: "Cake 495",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6777.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 496,
    name: "Cake 496",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6807.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 497,
    name: "Cake 497",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6843.jpg",
    category: "vanilla",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  },
  {
    id: 498,
    name: "Cake 498",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_6868.jpg",
    category: "fruit",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Buttercream",
    cakeShape: "Round"
  },
  {
    id: 499,
    name: "Cake 499",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_7017.jpg",
    category: "specialty",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Whipped Cream",
    cakeShape: "Custom"
  },
  {
    id: 500,
    name: "Cake 500",
    description: "Delicious cake",
    image: "/assets/images/products/IMG_7173.jpg",
    category: "chocolate",
    occasions: ["all", "birthday", "wedding", "anniversary", "custom"],
    longDescription: "",
    ingredients: [],
    frostingType: "Fondant",
    cakeShape: "Square"
  }
];

// Function to get products by category
export const getProductsByCategory = (category) => {
  return category === 'all' 
    ? products 
    : products.filter(product => product.category === category);
};

// Function to get product by ID
export const getProductById = (id) => {
  const productId = parseInt(id);
  return products.find(product => product.id === productId);
};

// Function to get related products (same category, excluding current product)
export const getRelatedProducts = (productId) => {
  const currentProduct = getProductById(productId);
  
  if (!currentProduct) return [];
  
  return products
    .filter(product => product.category === currentProduct.category && product.id !== currentProduct.id)
    .slice(0, 3);
};

// Get unique categories for filter buttons
export const getCategories = () => {
  const categories = [
    'Birthday Cakes',
    'Roll Cakes',
    'Dubai Chocolate',
    'Mini Cakes',
    'Desserts in a Cup',
    'Classic Desserts',
    'Custom Cakes',
    'Occasion Cakes',
    'Fruit Cakes'
  ];
  return categories;
};

// Get unique cake shapes for filter buttons
export const getCakeShapes = () => {
  const shapes = ['Round', 'Square', 'Heart', 'Custom'];
  return shapes;
};

// Get unique frosting types for filter buttons
export const getFrostingTypes = () => {
  const frostingTypes = ['Fondant', 'Whipped Cream', 'Buttercream'];
  return frostingTypes;
};

// Get unique occasions
export const getOccasions = () => {
  const occasions = ['all', 'birthday', 'wedding', 'anniversary', 'custom'];
  return occasions;
};

// Get products by frosting type
export const getProductsByFrostingType = (frostingType) => {
  return frostingType === 'all' 
    ? products 
    : products.filter(product => product.frostingType === frostingType);
};

// Get products by cake shape
export const getProductsByShape = (shape) => {
  return shape === 'all' 
    ? products 
    : products.filter(product => product.cakeShape === shape);
};

// Function to get products by both category and shape
export const getProductsByCategoryAndShape = (category, shape) => {
  let filteredProducts = products;
  
  if (category !== 'all') {
    filteredProducts = filteredProducts.filter(product => product.category === category);
  }
  
  if (shape !== 'all') {
    filteredProducts = filteredProducts.filter(product => product.cakeShape === shape);
  }
  
  return filteredProducts;
};
